### ISSUE TITLE
iojs 2.x and above

### ISSUE THREAD

**Issue by timoxley** [zenoamaro/ansible-iojs#1]
Sadly can't yet use 2.x with this playbook and [3.0 is soon to be released](https://github.com/nodejs/io.js/issues/1807).

**Comment by zenoamaro** [comment]
Hi, I'll look at it soon.

In the mean time, are you able to switch version by setting something like this?

``` yml
iojs_version: '2.3.*'
```

Let me know if this doesn't work.

**Comment by timoxley** [comment]
@zenoamaro yep tried that, it not work:

```
TASK: [zenoamaro.iojs | Installing io.js] *************************************
failed: [staging] => {"failed": true}
stderr: E: Version '2.3.*' for 'iojs' was not found

stdout: Reading package lists...
Building dependency tree...
Reading state information...

msg: '/usr/bin/apt-get -y -o "Dpkg::Options::=--force-confdef" -o "Dpkg::Options::=--force-confold"   install 'iojs=2.3.*'' failed: E: Version '2.3.*' for 'iojs' was not found


FATAL: all hosts have already failed -- aborting
```

**Comment by timoxley** [comment]
Looks like this may be the culprit:

``` yml
  apt_repository:
    repo: "deb https://deb.nodesource.com/iojs_1.x {{ansible_distribution_release}} main"
```

https://github.com/zenoamaro/ansible-iojs/blob/3d4ab2f074252d6f1382ff36b55d80c0892608ac/tasks/install.yml#L29-L30

**Comment by zenoamaro** [comment]
Yeah, looks like we have to switch the repository based on the major.

I'll see to fix that in a minute. Thanks for noticing.

**Comment by zenoamaro** [comment]
v0.2.0 should be in galaxy in a minute or two.

Let me know if this solves your issue.

**Comment by timoxley** [comment]
Appears to have worked, thanks! :+1:
